USE [CMS]
GO

/****** Object:  Table [dbo].[MEMBER_SAVINGS_ACCOUNT_SETTINGS]    Script Date: 09/11/2014 03:50:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MEMBER_SAVINGS_ACCOUNT_SETTINGS](
	[MemberTypeNo] [int] NOT NULL,
	[NoSavingsAccount] [int] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[DateModified] [datetime] NOT NULL,
 CONSTRAINT [PK_MEMBER_SAVINGS_ACCOUNT_SETTINGS] PRIMARY KEY CLUSTERED 
(
	[MemberTypeNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

