USE [CMS]
GO

/****** Object:  Table [dbo].[PAYMENT_AMORTIZATION]    Script Date: 09/11/2014 13:56:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAYMENT_AMORTIZATION](
	[ORNo] [int] NOT NULL,
	[AmortizationId] [int] NOT NULL,
	[Amount] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_PAYMENT_AMORTIZATION] PRIMARY KEY CLUSTERED 
(
	[ORNo] ASC,
	[AmortizationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PAYMENT_AMORTIZATION]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_AMORTIZATION_LOAN_AMORTIZATION] FOREIGN KEY([AmortizationId])
REFERENCES [dbo].[LOAN_AMORTIZATION] ([AmortizationId])
GO

ALTER TABLE [dbo].[PAYMENT_AMORTIZATION] CHECK CONSTRAINT [FK_PAYMENT_AMORTIZATION_LOAN_AMORTIZATION]
GO

ALTER TABLE [dbo].[PAYMENT_AMORTIZATION]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_AMORTIZATION_PAYMENT] FOREIGN KEY([ORNo])
REFERENCES [dbo].[PAYMENT] ([ORNo])
GO

ALTER TABLE [dbo].[PAYMENT_AMORTIZATION] CHECK CONSTRAINT [FK_PAYMENT_AMORTIZATION_PAYMENT]
GO

