USE [CMS]
GO

/****** Object:  Table [dbo].[TIME_DEPOSIT]    Script Date: 09/17/2014 23:23:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIME_DEPOSIT](
	[CertificateNo] [varchar](15) NOT NULL,
	[AccountNo] [varchar](15) NOT NULL,
	[DepositAmount] [decimal](18, 2) NOT NULL,
	[Maturity] [date] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_TIME_DEPOSIT_1] PRIMARY KEY CLUSTERED 
(
	[CertificateNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TIME_DEPOSIT]  WITH CHECK ADD  CONSTRAINT [FK_TIME_DEPOSIT_MEMBER] FOREIGN KEY([AccountNo])
REFERENCES [dbo].[MEMBER] ([AccountNo])
GO

ALTER TABLE [dbo].[TIME_DEPOSIT] CHECK CONSTRAINT [FK_TIME_DEPOSIT_MEMBER]
GO

