USE [CMS]
GO

/****** Object:  Table [dbo].[PAYMENT_BALANCE]    Script Date: 9/18/2014 6:37:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAYMENT_BALANCE](
	[ORNo] [int] NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[Penalty] [decimal](18, 2) NOT NULL,
	[Interest] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_PAYMENT_BALANCE] PRIMARY KEY CLUSTERED 
(
	[ORNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PAYMENT_BALANCE]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_BALANCE_PAYMENT] FOREIGN KEY([ORNo])
REFERENCES [dbo].[PAYMENT] ([ORNo])
GO

ALTER TABLE [dbo].[PAYMENT_BALANCE] CHECK CONSTRAINT [FK_PAYMENT_BALANCE_PAYMENT]
GO

