USE [CMS]
GO

/****** Object:  Table [dbo].[LOAN_AMORTIZATION]    Script Date: 09/11/2014 13:57:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOAN_AMORTIZATION](
	[AmortizationId] [int] IDENTITY(1,1) NOT NULL,
	[LoanApplicationId] [int] NOT NULL,
	[AmortizationDueDate] [date] NOT NULL,
	[Amount] [decimal](10, 2) NOT NULL,
	[isPaid] [bit] NULL,
	[Penalty] [decimal](10, 2) NULL,
 CONSTRAINT [PK_LOAN_AMORTIZATION] PRIMARY KEY CLUSTERED 
(
	[AmortizationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LOAN_AMORTIZATION]  WITH CHECK ADD  CONSTRAINT [FK_LOAN_AMORTIZATION_LOAN_INFORMATION] FOREIGN KEY([LoanApplicationId])
REFERENCES [dbo].[LOAN_INFORMATION] ([LoanApplicationId])
GO

ALTER TABLE [dbo].[LOAN_AMORTIZATION] CHECK CONSTRAINT [FK_LOAN_AMORTIZATION_LOAN_INFORMATION]
GO

